version: "3.8"

services:
  backend:
    build: ./server
    container_name: basic-container
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
